### ISSUE TITLE
error when run BurnIn.xml

### ISSUE THREAD

**Issue by liamxg** [suchard-group/EBOVPhyloHawkes#2]
Fatal exception: dr.evolution.util.Taxa cannot be cast to dr.inference.model.Parameter
java.lang.ClassCastException: dr.evolution.util.Taxa cannot be cast to dr.inference.model.Parameter
	at dr.inference.hawkes.HawkesLikelihood$1.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

**Comment by liamxg** [comment]
@andrewjholbrook

**Comment by xji3** [comment]
@liamxg You probably want to use `hawkes` branch of BEAST.  You also need to build the hawkes compute library from `https://github.com/suchard-group/hawkes` and use the `randomRates` branch.  Please let me know if it could run afterwards.

**Comment by liamxg** [comment]
@xji3 thanks.
